- name: Upgrade all packages
  yum:
    name: * 
    state: latest

- name: Install k3s using  command
  command: curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--flannel-backend=none --cluster-cidr=192.168.0.0/16 --disable-network-policy --disable=traefik --kube-apiserver-arg=feature-gates=SCTPSupport=true --service-node-port-range=2000-36767" sh -

